[package]
name = "tower-sessions-file-store"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = ["fs"] }
tower-sessions = "0.13.0"
